# TensorFlow

```sh
# Install
pip install tensorflow
```

If you have a CUDA enabled GPU, you can install the GPU version of TensorFlow.

[And maybe some other stuff](https://www.tensorflow.org/install/gpu) 

```sh
pip install tensorflow-gpu
```

## Importing TensorFlow

In [1]:
import tensorflow as tf
# print(tf.__version__)
print(tf.version.VERSION)

2023-02-17 12:13:47.127912: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


2.11.0


## Tensors 

Are vectors and matrices. (https://www.tensorflow.org/guide/tensor)

Each tensor represents a partialy defined computation that will eventually produce a value.

TensorFlow programs work by building a graph of Tensor objects that details how tensors are related.

### Each tensor has a data type and a shape.

**Data Types Include**: `float32, int32, string` and others.

**Shape**: Represents the dimension of data.

## Creating Tensors

Define the value of the **tensor** and the **datatype**, and you're good to go!

[full list of datatypes](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType?version=stable)

In [2]:
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

# These tensors have a shape of 1, which means they're a "scalar" - one value.  Versus vector value & matrices.
print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


2023-02-17 12:14:00.613127: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Rank [Degree] of Tensors

The number of dimensions involved in the tensor. What we created above is a *tensor of rank 0*, also known as a scalar.

0 dimensionality; one value.  Versus an array.

In [3]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

print("One list, one array, one dimension; a vector:\n", rank1_tensor)
print("\nLists inside of a list, a matrix:\n", rank2_tensor)
# Deepest level of a nested list is the rank

One list, one array, one dimension; a vector:
 <tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Test'], dtype=object)>

Lists inside of a list, a matrix:
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'test', b'ok'],
       [b'test', b'yes']], dtype=object)>


**To determine the rank** of a tensor we can call the following method.

In [4]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

### Tip!

If it says: `Can't convert non-rectangular Python sequence to tensor`, it means you screwed up the number of elements somewhere.

In [6]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

## Shape of Tensors

How many items we have in each dimension.

2 elements in the 1st dimension, 2 elements in the 2nd dimension:

In [7]:
rank2_tensor.shape

TensorShape([2, 2])

In [8]:
rank1_tensor.shape # Because it's a rank 1, we only get 1 number

TensorShape([1])

## Changing Shape

The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [9]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,2]
                                                                             
# The number of elements in the reshaped tensor MUST match the number in the original

print("tensor1:", tensor1)
print("\ntensor2:", tensor2)
print("\ntensor3:", tensor3)
# Notice the changes in shape

tensor1: tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)

tensor2: tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)

tensor3: tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


`tensor1` (1, 2, 3) has 1 interior list, and 2 lists inside of that list, and 3 elements in each of those lists.

```json
[
  [
    [1, 1, 1],
    [1, 1, 1]
  ]
]
```

`tensor2` (2, 3, 1) we have 2 lists, inside of those we have 3 lists, and 1 element inside each of those lists.

```json
[
  [
    [1], [1], [1]
  ],
  [
    [1], [1], [1]
  ]
]
```

`tensor3` with the `-1` means: *you* figure it out!

3 * 2 = 6

(3, 2) means we have 3 lists in there, with 2 things in each list.

```json
[
  [1, 1],
  [1, 1],
  [1, 1]
]
```

### <span style="color:blue">Slicing Tensors</span>

<span style="color:blue">The slice operator can be used on tensors to select specific axes or elements.

<span style="color:blue">Example:</span>

```py
tensor[dim1, dim2, dim3]
```


In [10]:
# Creating a 2D tensor
matrix = [
  [1, 2, 3, 4, 5],
  [6, 7, 8, 9, 10],
  [11, 12, 13, 14, 15],
  [16, 17, 18, 19, 20]
]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print("rank:", tf.rank(tensor))
print("\nshape:", tensor.shape)

rank: tf.Tensor(2, shape=(), dtype=int32)

shape: (4, 5)


In [14]:
# Now let's select some different rows and columns from our tensor

three = tensor[0, 2]      # selects the 3rd element from the 1st row
print("\n3rd element:", three)  # -> 3

row1 = tensor[0]          # selects the first row
print("\n1st row:", row1)

column1 = tensor[:, 0]    # selects the first column
print("\n1st column:", column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print("\nrows 2 and 4:", row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print("\n1st column, rows 2 and 3:", column_1_in_row_2_and_3)


3rd element: tf.Tensor(3, shape=(), dtype=int32)

1st row: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)

1st column: tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)

rows 2 and 4: tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)

1st column, rows 2 and 3: tf.Tensor([ 6 11], shape=(2,), dtype=int32)


## Types of Tensors

- Variable
- Constant
- Placeholder
- SparseTensor

With the execption of ```Variable``` all these tensors are immutable.

We use the Variable tensor when we want to change the value of our tensor.

## Evaluating tensors

```py
with tf.session() as sess:  # Creates session, uses default graph
    tensor.eval()           # "tensor" is the name of your tensor
```

# Sources
Most of the information is taken direclty from the TensorFlow website which can be found below.

https://www.tensorflow.org/guide/tensor