# Demystifying the Math Behind Machine Learning

In [1]:
import numpy as np

y = np.array([44, 21, 37])

print("\ny shape:", y.shape)  # an array of 3 things



y shape: (3,)


In [2]:
X = np.array([
    [1.1, 1, 545, 1],
    [4.6, 0, 345, 2],
    [7.2, 1, 754, 3]
])

print("\nX shape:", X.shape)  # 3 samples with 4 things in it



X shape: (3, 4)


In [3]:
# Reshape
arr = np.array([1.1, 1, 545, 1, 4.6, 0, 345, 2, 7.2, 1, 754, 3])

print("\narr shape:", arr.shape)

X = arr.reshape(3, 4)

print("\nreshape:", X.shape)


arr shape: (12,)

reshape: (3, 4)


In [4]:
# Matrix subtraction
a = np.array([[1, 1], [1, 0]])
b = np.array([[1, 0], [0, 1]])

print(a - b)


[[ 0  1]
 [ 1 -1]]


In [5]:
# Matrix multiplication
a = np.array([[0, 1], [1, -1]])

print(a * -2)


[[ 0 -2]
 [-2  2]]


In [6]:
# Dot product
X = np.array([[4, 5], [2, 4], [3, 3]])
b = np.array([3, -2])

print(np.dot(X, b))


[ 2 -2  3]


In [7]:
B = np.array([[3, -2], [-2, 5]])

print(np.dot(X, B))


[[ 2 17]
 [-2 16]
 [ 3  9]]


In [8]:
# Transpose
X.transpose()


array([[4, 2, 3],
       [5, 4, 3]])